spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/shopflow_dev
spring.datasource.username=root
spring.datasource.password=shopflow
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration